[package]
name = "math"
version = "0.1.0"
edition = "2024"

[dependencies]
# Workspace dependencies
bevy.workspace = true
serde.workspace = true
fxhash.workspace = true

# Local dependencies
rand = "0.9.2"
