[package]
name = "protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
bevy.workspace = true
serde.workspace = true
ciborium.workspace = true
fxhash.workspace = true
serde_json.workspace = true
bytemuck.workspace = true
zip.path = "../zip"
